variables:
  AWS_ACCESS_KEY_ID: $TF_VAR_aws_access_key_id
  AWS_SECRET_ACCESS_KEY: $TF_VAR_aws_secret_access_key
  AWS_REGION: ap-southeast-2

before_script:
  - python3 --version
  - pylint --version
  - aws --version

stages:
  - test
  - build
  - deploy

lint:
  retry: 2
  tags:
    - python
  stage: test
  script:
    - pip install -q -U pylint
    # - make lint
  only:
    refs:
      - merge_request

build-package:
  retry: 2
  tags:
    - python
  stage: build
  script:
    - pip install -q -U setuptools wheel
    - make package
  only:
    refs:
      - merge_request

build-artifacts:
  retry: 2
  tags:
    - python
  stage: build
  script:
    - make cloudformation-upload
    - make update-proxy
    - pip install -q -U setuptools wheel
    - make package-upload
  only:
    refs:
      - main

